version: "3.9"
services:
  openplc:
    #build: 
     #context: ./OpenPLC_v2
     #dockerfile: Dockerfile
    image: nikhilkc96/openplc
    stdin_open: true # docker run -i
    tty: true 
    privileged: true
    container_name: openplc
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - 8080:8080
      - 505:502
    networks:
     wnet:
        ipv4_address: 192.168.0.26
     fnet:
        ipv4_address: 192.168.1.13
  

  openplc_hmi:
    build: 
      context: ./hmi
      dockerfile: Dockerfile
    stdin_open: true # docker run -i
    tty: true 
    privileged: true
    entrypoint: ["gunicorn", "app:app", "-b", "0.0.0.0:5000"]
    container_name:  openplc_hmi
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - 5000:5000
    networks:
     wnet:
        ipv4_address: 192.168.0.27


  openplc_simulation:
    container_name: openplc_sim_server
    build: 
      context: ./openplc_sim
      dockerfile: Dockerfile
    stdin_open: true # docker run -i
    tty: true 
    privileged: true
    # entrypoint: ["python3", "tcp_modbus.py"]
    networks:
     wnet:
       ipv4_address: 192.168.0.28


networks:
  wnet:
    driver: bridge
    name: icsnet
    ipam:
     config:
       - subnet: 192.168.0.0/24
         gateway: 192.168.0.1
    driver_opts:
      com.docker.network.bridge.name: br_icsnet
  fnet:
    driver: bridge
    name: phynet
    ipam:
     config:
       - subnet: 192.168.1.0/24
         gateway: 192.168.1.1 
    driver_opts:
      com.docker.network.bridge.name: br_phynet


