version: "3.9"
services:
  openplc:
    # build: 
    #  context: ./openplc
    #  dockerfile: Dockerfile
    image: nikhilkc96/openplc
    stdin_open: true # docker run -i
    tty: true 
    privileged: true
    container_name: openplc
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - 8080:8080
      - 502:502
    networks:
     wnet:
        ipv4_address: 192.168.0.26
     fnet:
        ipv4_address: 192.168.1.13
  

  openplc_hmi:
    build: 
      context: ./hmi
      dockerfile: Dockerfile
    stdin_open: true # docker run -i
    tty: true 
    privileged: true
    container_name:  openplc_hmi
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - 5000:5000
    networks:
     wnet:
        ipv4_address: 192.168.0.27


  opemplc_simulation:
    container_name: openplc_sim_server
    build: ./server
    ports: 
      - "7799:7799"
      - "9977:9977"
    wnet:
        ipv4_address: 192.168.0.28

  openplc_gateway:
    container_name: openplc_sim_gateway
    build: ./gateway
    ports:
      - "5020:5020"
    wnet:
        ipv4_address: 192.168.0.29

networks:
  wnet:
    driver: bridge
    name: icsnet
    ipam:
     config:
       - subnet: 192.168.0.0/24
         gateway: 192.168.0.1
    driver_opts:
      com.docker.network.bridge.name: br_icsnet
  fnet:
    driver: bridge
    name: phynet
    ipam:
     config:
       - subnet: 192.168.1.0/24
         gateway: 192.168.1.1 
    driver_opts:
      com.docker.network.bridge.name: br_phynet


