x-os_instance: &_os_instance
    image: opensearchproject/opensearch:2.3.0
    ulimits:
        nofile:
            soft: 65535
            hard: 65535
        memlock:
            soft: -1
            hard: -1
    networks:
        - arkime-os


services:
    os01:
        <<: *_os_instance
        container_name: os01
        environment:
            - node.name=os01
            - discovery.seed_hosts=os02,os03
            # default
            - cluster.name=os-arkime-cluster
            - cluster.initial_master_nodes=os01,os02,os03
            - bootstrap.memory_lock=true
            - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
            - DISABLE_SECURITY_PLUGIN=true
            - DISABLE_INSTALL_DEMO_CONFIG=true
        volumes:
            - os1_data:/usr/share/opensearch/data
    os02:
        <<: *_os_instance
        container_name: os02
        environment:
            - node.name=os02
            - discovery.seed_hosts=os01,os03
            # default
            - cluster.name=os-arkime-cluster
            - cluster.initial_master_nodes=os01,os02,os03
            - bootstrap.memory_lock=true
            - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
            - DISABLE_SECURITY_PLUGIN=true
            - DISABLE_INSTALL_DEMO_CONFIG=true
        volumes:
            - os2_data:/usr/share/opensearch/data
    os03:
        <<: *_os_instance
        container_name: os03
        environment:
            - node.name=os03
            - discovery.seed_hosts=os01,os02
            # default
            - cluster.name=os-arkime-cluster
            - cluster.initial_master_nodes=os01,os02,os03
            - bootstrap.memory_lock=true
            - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
            - DISABLE_SECURITY_PLUGIN=true
            - DISABLE_INSTALL_DEMO_CONFIG=true
        volumes:
            - os3_data:/usr/share/opensearch/data

    arkime:
        build:
            context: arkime-docker/.
            dockerfile: Dockerfile
        depends_on:
            - os01
            - os02
            - os03
        environment:
            - OS_HOST=os01
            - OS_PORT=9200
        ports:
            - 8005:8005
        volumes:
            - arkime_config:/data/config
            - arkime_logs:/data/logs
            - arkime_pcap:/data/pcap
        networks:
            - arkime-os
            - hostnetwork

volumes:
    arkime_config:
    arkime_logs:
    os1_data:
    os2_data:
    os3_data:
    arkime_pcap:

networks:
    arkime-os:
    hostnetwork:
        external: true
        name: host