cluster.name: "docker-cluster"
network.host: 0.0.0.0

# this value is required because we set "network.host"
# be sure to modify it appropriately for a production cluster deployment
discovery.seed_hosts: ["127.0.0.1", "[::1]"]
# node.master: true
# node.ingest: true
# node.data: true

action.auto_create_index: .security,.monitoring*,.watches,.triggered_watches,.watcher-history*,.ml*
# discovery.type: "single-node"

# bin/elasticsearch-keystore create
# echo "changeme" | bin/elasticsearch-keystore add -x 'bootstrap.password'

# xpack.security.authc.accept_default_password: true
# xpack.security.transport.ssl.enabled: false
# http -a elastic:changeme localhost:9200
# curl -u elastic:changeme http://127.0.0.1:9200

# bin/x-pack/setup-passwords \
# auto --batch \
# -Expack.ssl.certificate=x-pack/certificates/es01/es01.crt \
# -Expack.ssl.certificate_authorities=x-pack/certificates/ca/ca.crt \
# -Expack.ssl.key=x-pack/certificates/es01/es01.key \
# --url https://localhost:9200
