version: "3.9"
services:
  elasticsearch:
    image: blacktop/elasticsearch:x-pack-7.4.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - elastinet

  kibana:
    depends_on:
      - elasticsearch
    image: blacktop/kibana:x-pack-7.4.0
    environment:
      - xpack.reporting.enabled=false
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    networks:
      - elastinet

  filebeat:
    depends_on:
      - kibana
    image: blacktop/filebeat:7.4.0
    links:
      - kibana
      - elasticsearch
    volumes:
      - ./pcap:/pcap
    command: -e
    networks:
      - elastinet

  zeek:
    depends_on:
      - filebeat
    build: ./elastic
    image: blacktop/zeek:elastic
    volumes:
      - ./pcap:/pcap
    cap_add:
      - NET_RAW
    network_mode: "host"
    command: -i af_packet::eth0 local


networks:
  elastinet:
    driver: bridge
    name: elastinet
    ipam:
     config:
       - subnet: 192.168.3.0/24
         gateway: 192.168.3.1
    driver_opts:
      com.docker.network.bridge.name: elastinet