version: "3.9"
services:
  elasticsearch:
    build: 
     context: ./elasticsearch
     dockerfile: Dockerfile
    stdin_open: true # docker run -i
    tty: true 
    privileged: true
    environment:
      # - bootstrap.memory_lock=true
      - discovery.type=single-node
      # - ELASTICSEARCH_USERNAME=elastic
      # - ELASTIC_PASSWORD=Virtue@123
      # - xpack.security.enabled=true
      #  - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - elastinet

  kibana:
    depends_on:
      - elasticsearch
    build: 
     context: ./kibana
     dockerfile: Dockerfile
    stdin_open: true # docker run -i
    tty: true 
    privileged: true
    # environment:
    #   - ELASTICSEARCH_USERNAME=elastic
    #   - ELASTICSEARCH_PASSWORD=Virtue@123
    - xpack.reporting.enabled=false
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    networks:
      - elastinet

  filebeat:
    depends_on:
      - kibana
    build: 
     context: ./filebeat
     args:
             VERSION : 7.7.1
     dockerfile: Dockerfile
    stdin_open: true # docker run -i
    tty: true 
    privileged: true
    # environment:
    #   - ELASTICSEARCH_USERNAME=elastic
    #   - ELASTICSEARCH_PASSWORD=Virtue@123
    links:
      - kibana
      - elasticsearch
    volumes:
      - pcap:/pcap
    command: -e
    networks:
      - elastinet

  zeek:
    # depends_on:
    #   - filebeat
    build: 
     context: ./zeek/elastic
     dockerfile: Dockerfile
    stdin_open: true # docker run -i
    tty: true 
    privileged: true
    volumes:
      - pcap:/pcap
    cap_add:
      - NET_RAW
    network_mode: "host"
    # command: zeek -i af_packet::eth0 local
    entrypoint: ["zeek", "-i", "af_packet::eth0", "local" ]

networks:
  elastinet:
    driver: bridge
    name: elastinet
    ipam:
     config:
       - subnet: 192.168.3.0/24
         gateway: 192.168.3.1
    driver_opts:
      com.docker.network.bridge.name: elastinet



volumes:
    pcap: