name: ZipFiles
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Zip Folder
      run: zip -r ${{ github.workspace }}/bottlefactory/src/src.zip ${{ github.workspace }}/bottlefactory/src/
    - name: Release to Github
      run: echo "Release"
