name: Zip Files

on:
  push:
  pull_request:

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: bottlefactory/src/
          dest: bottlefactory/src/src.zip
